version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000" #listenning on the app
    volumes:
      - './public/images:/usr/src/myapp/public/images'  #first volume
    links:
    - redis
  redis:
    image: redis
    ports:
    - "6379:6379"  #default port for redis
    command:
    - "--appendonly yes" #add persistant command line
    volumes:
    - './data:/data'  #second volume
